const crypto = require("crypto");
const APS_AUTH_BASE = "https://developer.api.autodesk.com/authentication/v2";
const AUTH_COOKIE = "aps_auth";
function cfg(){const c=process.env.APS_CLIENT_ID,s=process.env.APS_CLIENT_SECRET,cb=process.env.APS_CALLBACK_URL,sc=process.env.APS_SCOPES||"data:read data:write account:read";const m=[];if(!c)m.push("APS_CLIENT_ID");if(!s)m.push("APS_CLIENT_SECRET");if(!cb)m.push("APS_CALLBACK_URL");if(m.length)throw new Error(`Missing .env values: ${m.join(", ")}`);return{clientId:c,clientSecret:s,callbackUrl:cb,scopes:sc};}
function secret(){return process.env.SESSION_SECRET||"dev-secret-change-me"}
function basic(id,sec){return "Basic "+Buffer.from(`${id}:${sec}`).toString("base64")}
function sign(v){return crypto.createHmac("sha256",secret()).update(v).digest("base64url")}
function createOAuthState(){const n=crypto.randomBytes(16).toString("hex");return `${n}.${sign(n)}`}
function validateOAuthState(st){if(!st||typeof st!=="string")return false;const [n,s]=st.split(".");if(!n||!s)return false;const e=sign(n);try{return crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e))}catch{return false}}
function enc(v){const key=crypto.createHash("sha256").update(secret()).digest(),iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",key,iv),p=Buffer.from(JSON.stringify(v));const encrypted=Buffer.concat([c.update(p),c.final()]);return Buffer.concat([iv,c.getAuthTag(),encrypted]).toString("base64url")}
function dec(v){try{const raw=Buffer.from(v||"","base64url"),iv=raw.subarray(0,12),tag=raw.subarray(12,28),encrypted=raw.subarray(28),key=crypto.createHash("sha256").update(secret()).digest(),d=crypto.createDecipheriv("aes-256-gcm",key,iv);d.setAuthTag(tag);return JSON.parse(Buffer.concat([d.update(encrypted),d.final()]).toString("utf8"))}catch{return null}}
function cookies(req){const out={};for(const p of String(req.headers.cookie||"").split(";")){const i=p.indexOf("=");if(i>-1)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
function opts(max){const secure=String(process.env.APS_CALLBACK_URL||"").startsWith("https://");return [`Path=/`,`HttpOnly`,`SameSite=Lax`,secure?"Secure":"",`Max-Age=${max}`].filter(Boolean).join("; ")}
function setAuthCookie(res,state){res.setHeader("Set-Cookie",`${AUTH_COOKIE}=${encodeURIComponent(enc(state))}; ${opts(60*60*24*7)}`)}
function clearAuthCookie(res){res.setHeader("Set-Cookie",`${AUTH_COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0`)}
function getAuthFromRequest(req){return dec(cookies(req)[AUTH_COOKIE])}
function buildAuthorizeUrl(state){const {clientId,callbackUrl,scopes}=cfg();return `${APS_AUTH_BASE}/authorize?`+new URLSearchParams({response_type:"code",client_id:clientId,redirect_uri:callbackUrl,scope:scopes,state}).toString()}
async function exchangeCodeForToken(code){const {clientId,clientSecret,callbackUrl}=cfg();const body=new URLSearchParams({grant_type:"authorization_code",code,redirect_uri:callbackUrl});const r=await fetch(`${APS_AUTH_BASE}/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Authorization:basic(clientId,clientSecret)},body});if(!r.ok)throw new Error(`Token exchange failed (${r.status}): ${await r.text()}`);return r.json()}
async function refreshToken(refresh_token){const {clientId,clientSecret,scopes}=cfg();const body=new URLSearchParams({grant_type:"refresh_token",refresh_token,scope:scopes});const r=await fetch(`${APS_AUTH_BASE}/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Authorization:basic(clientId,clientSecret)},body});if(!r.ok)throw new Error(`Token refresh failed (${r.status}): ${await r.text()}`);return r.json()}
async function ensureValidToken(req,res,next){let aps=getAuthFromRequest(req);if(!aps?.refresh_token)return res.status(401).json({error:"Not signed in to Autodesk"});if(Date.now()<aps.expires_at-60000){req.aps=aps;return next()}try{const fresh=await refreshToken(aps.refresh_token);aps={access_token:fresh.access_token,refresh_token:fresh.refresh_token||aps.refresh_token,expires_at:Date.now()+fresh.expires_in*1000};setAuthCookie(res,aps);req.aps=aps;return next()}catch{clearAuthCookie(res);return res.status(401).json({error:"Session expired, sign in again"})}}
module.exports={buildAuthorizeUrl,exchangeCodeForToken,ensureValidToken,createOAuthState,validateOAuthState,setAuthCookie,clearAuthCookie,getAuthFromRequest};
