const ExcelJS=require('exceljs');
const norm=v=>String(v||'').trim().toLowerCase();
const clean=v=>norm(v).replace(/\s+/g,' ');
const HEAD=['Project','Reference Number','Supplier Company','Expense Name','Payment Reference','Payment Type','Type','Issue Date','Received Date','Paid Date','Budget','Purchase Order Name','Line Item Name','Quantity','Unit','Unit Price','Amount','Status'];
const projectLabel=p=>p.name||p.id;
const budgetLabel=b=>`${b.code||'No Code'} - ${b.name||b.id}`;
const contractLabel=c=>c.name||c.number||c.id;
function value(row,map,name){const i=map[norm(name)];if(!i)return'';const v=row.getCell(i).value;if(v==null)return'';if(v instanceof Date)return v;if(typeof v==='object'&&v.result!==undefined)return String(v.result).trim();return String(v).trim()}
function iso(v,n,r){if(!v)return'';if(v instanceof Date)return v.toISOString();const s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}$/.test(s))return`${s}T00:00:00.000Z`;const d=new Date(s);if(!isNaN(d))return d.toISOString();throw Error(`Invalid ${n} on row ${r}`)}
function num(v,n,r,d=0){if(v===''||v==null)return d;const x=Number(v);if(isNaN(x))throw Error(`Invalid ${n} on row ${r}`);return x}
function ids(value){if(!value)return[];if(Array.isArray(value))return value.flatMap(x=>typeof x==='string'?[x]:[x?.id,x?.budgetId,x?.contractId]).filter(Boolean);return typeof value==='string'?[value]:[]}
function buildLinks(projects,budgetsByProject,contractsByProject){const links=[];for(const p of projects){const budgets=budgetsByProject[p.id]||[],contracts=contractsByProject[p.id]||[];for(const c of contracts){const budgetIds=new Set([...ids(c.budgetIds),...ids(c.budgets),...ids(c.linkedBudgetIds),...ids(c.budgetId)]);for(const b of budgets){const contractIds=new Set([...ids(b.contractIds),...ids(b.contracts),...ids(b.linkedContractIds),...ids(b.contractId)]);if(budgetIds.has(b.id)||contractIds.has(c.id))links.push({projectId:p.id,projectName:projectLabel(p),budgetId:b.id,budgetName:budgetLabel(b),contractId:c.id,contractName:contractLabel(c)})}}}return links}
async function build({projects,budgetsByProject,contractsByProject,companies=[]}){const wb=new ExcelJS.Workbook(),s=wb.addWorksheet('Expenses'),links=buildLinks(projects,budgetsByProject,contractsByProject);s.addRow(HEAD);const p=projects[0]||{name:'Select project',id:''},b=(budgetsByProject[p.id]||[])[0];s.addRow([projectLabel(p),'REF-0001',companies[0]?.name||'','Supplier - Claim 001','PAY-001','EFT','Invoice','2026-08-01','2026-08-02','2026-08-13',b?budgetLabel(b):'Select budget','', 'Labour',1,'ls',5000,{formula:'N2*P2',result:5000},'paid']);s.getRow(1).font={bold:true};s.getCell('K1').note='Select a Budget, then select an optional Purchase Order. Preview validates whether the pair is linked in Autodesk Forma.';s.getCell('L1').note='Purchase Order is optional. The dropdown is selectable; invalid Budget / PO pairs are blocked during Preview.';s.views=[{state:'frozen',ySplit:1}];s.autoFilter={from:'A1',to:'R1'};[30,16,28,30,18,16,12,14,14,14,40,32,26,10,10,12,12,12].forEach((w,i)=>s.getColumn(i+1).width=w);
const ps=wb.addWorksheet('Project Lookup');ps.addRow(['Name','ID']);projects.forEach(x=>ps.addRow([projectLabel(x),x.id]));ps.state='veryHidden';
const bs=wb.addWorksheet('Budget Lookup');bs.addRow(['Project','Name','ID']);for(const p of projects)for(const b of budgetsByProject[p.id]||[])bs.addRow([projectLabel(p),budgetLabel(b),b.id]);bs.state='veryHidden';
const cs=wb.addWorksheet('Contract Lookup');cs.addRow(['Project','Name','ID']);for(const p of projects)for(const c of contractsByProject[p.id]||[])cs.addRow([projectLabel(p),contractLabel(c),c.id]);cs.state='veryHidden';
const rs=wb.addWorksheet('Budget PO Relations');rs.addRow(['Project Budget Key','Project PO Key','Project','PO Name','Budget Name','Budget ID','Contract ID']);links.sort((a,b)=>(a.projectName+'|'+a.budgetName+'|'+a.contractName).localeCompare(b.projectName+'|'+b.budgetName+'|'+b.contractName)).forEach(x=>rs.addRow([`${x.projectName}|${x.budgetName}`,`${x.projectName}|${x.contractName}`,x.projectName,x.contractName,x.budgetName,x.budgetId,x.contractId]));rs.state='veryHidden';
const ss=wb.addWorksheet('Supplier Lookup');ss.addRow(['Name']);companies.forEach(c=>ss.addRow([c.name]));ss.state='veryHidden';
for(let r=2;r<=201;r++){s.getCell(`A${r}`).dataValidation={type:'list',formulae:[`'Project Lookup'!$A$2:$A$${Math.max(2,projects.length+1)}`]};s.getCell(`K${r}`).dataValidation={type:'list',allowBlank:false,showErrorMessage:true,errorTitle:'Select a budget',error:'Choose a Budget from the dropdown. Preview will validate the selected Purchase Order relationship.',formulae:[`'Budget Lookup'!$B$2:$B$${Math.max(2,bs.rowCount)}`]};s.getCell(`L${r}`).dataValidation={type:'list',allowBlank:true,showErrorMessage:true,errorTitle:'Select a purchase order',error:'Choose a Purchase Order from the dropdown or leave it blank. Preview will validate the Budget relationship.',formulae:[`'Contract Lookup'!$B$2:$B$${Math.max(2,cs.rowCount)}`]};if(companies.length)s.getCell(`C${r}`).dataValidation={type:'list',allowBlank:true,formulae:[`'Supplier Lookup'!$A$2:$A$${companies.length+1}`]};s.getCell(`R${r}`).dataValidation={type:'list',formulae:['"draft,approved,paid"']}}
return wb.xlsx.writeBuffer()}
async function parse(buffer,projects,budgets,contracts){const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer);const s=wb.getWorksheet('Expenses');if(!s)throw Error('Missing Expenses sheet');const map={};s.getRow(1).eachCell((c,i)=>map[norm(c.value)]=i);for(const n of['Project','Expense Name','Budget','Purchase Order Name','Line Item Name','Quantity','Unit Price','Amount'])if(!map[norm(n)])throw Error(`Missing column ${n}`);const pm=new Map(projects.map(p=>[clean(projectLabel(p)),p])),links=buildLinks(projects,budgets,contracts),sup=new Map(),rows=[],ignoredRows=[],invalidRows=[];let n=0,totalRows=0;s.eachRow((r,i)=>{if(i===1)return;const expenseName=value(r,map,'Expense Name'),itemName=value(r,map,'Line Item Name'),ref=value(r,map,'Reference Number');let supplier=value(r,map,'Supplier Company');if(!expenseName&&!itemName&&!ref&&!supplier)return;totalRows++;const qr=value(r,map,'Quantity'),ur=value(r,map,'Unit Price');if(qr===''&&ur===''){ignoredRows.push({excelRowNumber:i,reason:'Missing Quantity and Unit Price'});return}n++;const p=pm.get(clean(value(r,map,'Project')))||{id:'',name:value(r,map,'Project')},budgetText=value(r,map,'Budget'),poText=value(r,map,'Purchase Order Name');let budgetId='',contractId='';for(const b of budgets[p.id]||[])if(clean(budgetLabel(b))===clean(budgetText))budgetId=b.id;for(const c of contracts[p.id]||[])if(clean(contractLabel(c))===clean(poText))contractId=c.id;const projectLinks=links.filter(x=>x.projectId===p.id),linked=projectLinks.some(x=>x.budgetId===budgetId&&x.contractId===contractId);let relationshipValid=true,relationshipMessage='';if(poText&&projectLinks.length&&!linked){relationshipValid=false;relationshipMessage='The selected Budget and Purchase Order are not linked in Autodesk Forma.';invalidRows.push({excelRowNumber:i,projectName:p.name,budget:budgetText,purchaseOrder:poText,reason:relationshipMessage})}const key=`${p.id}|${clean(expenseName)}`;if(!supplier&&sup.has(key))supplier=sup.get(key);if(supplier&&!sup.has(key))sup.set(key,supplier);const quantity=num(qr,'Quantity',i,1),unitPrice=num(ur,'Unit Price',i,0),av=value(r,map,'Amount');rows.push({displayRowNumber:n,excelRowNumber:i,projectId:p.id,projectName:p.name,referenceNumber:ref,supplierName:supplier,expenseName,paymentReference:value(r,map,'Payment Reference'),paymentType:value(r,map,'Payment Type'),type:value(r,map,'Type')||'Invoice',issuedAt:iso(value(r,map,'Issue Date'),'Issue Date',i),receivedAt:iso(value(r,map,'Received Date'),'Received Date',i),paidAt:iso(value(r,map,'Paid Date'),'Paid Date',i),budgetId,budgetName:budgetText,purchaseOrderName:poText,contractId,itemName,quantity,unit:value(r,map,'Unit')||'ls',unitPrice,amount:av===''?quantity*unitPrice:num(av,'Amount',i),status:value(r,map,'Status')||'paid',relationshipValid,relationshipMessage})});return{rows,ignoredRows,invalidRows,summary:{totalRows,ignoredRows:ignoredRows.length,invalidRows:invalidRows.length,validRows:rows.filter(x=>x.relationshipValid).length,duplicateRows:0}}}
module.exports={build,parse,buildLinks};
